name: Java CI/CD with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # PR일 때는 빌드만, main 브랜치 push일 때만 배포
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      # Main 브랜치에 Push 될 때만 배포 실행
      - name: Copy JAR to Server
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/libs/youth_sketch_BE-0.0.1-SNAPSHOT.jar"
          target: "~/app"

      - name: Deploy and Restart Server
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 기존 jar 파일 삭제 후 새 파일로 이름 변경
            rm -f ~/app/ccsketch.jar
            mv ~/app/youth_sketch_BE-0.0.1-SNAPSHOT.jar ~/app/ccsketch.jar
            # systemd 서비스 재시작
            sudo systemctl restart ccsketch
            sudo systemctl status ccsketch --no-pager
